#!/bin/bash 
#
#SBATCH --job-name=hipatch_phy
#SBATCH --partition=jobs
#SBATCH --mem=10gb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=1000:00:00
#SBATCH --output=/home/taejoo/dsl_lab/Hi-Patch_taejoo/Hi-Patch/logs/hipatch_phy.log
#SBATCH --error=/home/taejoo/dsl_lab/Hi-Patch_taejoo/Hi-Patch/errs/hipatch_phy.err
#SBATCH --nodelist=gpusystem
#SBATCH --gres=gpu:1

source activate hipatch

bash /home/taejoo/dsl_lab/Hi-Patch_taejoo/Hi-Patch/scripts/run_phy.sh